project_id = "satsigmywganodvjcsip"

[functions.generate-referral]
verify_jwt = true

[functions.record-referral-deposit]
verify_jwt = true

[functions.record-commission-payment]
verify_jwt = true

[functions.send-referral-invitation]
verify_jwt = true

[functions.send-request-notification]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-email-verification]
verify_jwt = false

[functions.send-prayer-request]
verify_jwt = false
[functions.send-claim-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/send-claim-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-claim-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-claim-confirmation/*.html" ]
